name: 'ì½”ë“œ ë¦¬ë·°ì–´ í• ë‹¹'

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  reviewer:
    name: "Assign Reviewer"
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: HyungJu, h-beeen
          ready-comment: 'ì½”ë“œ ë¦¬ë·° ìš”ì²­í•©ë‹ˆë‹¤ ğŸ™† <reviewers>'
          merged-comment: 'ì„±ê³µì ìœ¼ë¡œ Merge ë˜ì—ˆìŠµë‹ˆë‹¤. Shout out to <reviewers> :wink:'
